### ISSUE TITLE
Application failed to stage

### ISSUE THREAD

**Issue by narendrachoudhary** [dmikusa-pivotal/cf-ex-phpmyadmin#2]
Hi dmikusa,

I have treid to upload your phpmyadmin but it is failing. I am running my own cloud foudry behind the proxies.

Thanks
Narendra

**Comment by dmikusa-pivotal** [comment]
Have you tried setting HTTP_PROXY & HTTPS_PROXY environment variables?  The example downloads PHPMyAdmin during the staging process, so it will need to be able to access the internet to do that.  If you set those environment variables, the downloader should pick them up and configure an HTTP Proxy.

If that doesn't work, you could do the following.  It would remove the need to download anything.

1.) Remove the `.extensions` folder from the project.
2.) Download PHPMyAdmin.  Extract the files to the `htdocs` folder, but don't overwrite `config.inc.php`.
3.) Remove the `htdocs/setup` directory.  It's not needed.
4.) Push your app.

It'll take longer to push, but as I mentioned above it won't try to download anything during staging.

If you are still stuck, set the `BP_DEBUG` environment variable to `True` and attach the output of `cf push` here.

**Comment by dmikusa-pivotal** [comment]
Open for a while with no response.  Closing.
