### ISSUE TITLE
Credentials example in README.md references nonexistent log file for PWS

### ISSUE THREAD

**Issue by menicosia** [dmikusa-pivotal/cf-ex-phpmyadmin#3]
Hi, this is Marco, the new PM working on the cf-mysql-release project at Pivotal. Thank you so much for this project and updating it recently - it's really helpful that this exists.

When I tried deploying this to PWS, everything worked fine till I got to, "If you need to find these, just run this command and look for the VCAP_SERVICES environment variable."

In this, it suggests to run `cf files` on logs/env.log. I couldn't find that file on PWS, perhaps I'm missing something.

BUT, I did find the VCAP_SERVICES variables pretty easily by clicking on the "Env Variables" tab in the Apps Manager. Not sure if that's a preferable solution?

-- Marco N.

**Comment by dmikusa-pivotal** [comment]
Marco,

Good catch.  CF removed the env.log file a while back and I forgot to update these docs.  The good news is that the process is easier now.  I've pushed an update with the correct instructions.

Dan

**Comment by menicosia** [comment]
Thanks!
